/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-01-25 12:05:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookingPage1_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1674643862407L));
    _jspx_dependants.put("jar:file:/D:/final-project(LAST)/carrotline/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(" \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<!-- CSS 영역 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/booking/bookingFirstPage.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/booking/chooseAirport.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/booking/bookingHeader.css\">  \r\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/booking/bookingHeader.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 캘린더 -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/booking/calStyle.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <!--소이언니가 준 script-->\r\n");
      out.write(" <script src='https://kit.fontawesome.com/77ad8525ff.js' crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--\r\n");
      out.write("    jQuery를 사용한 모든 웹페이지는 다음 코드로 시작합니다.\r\n");
      out.write("    $(document).ready()는 문서가 준비되면 매개변수로 넣은 콜백 함수를 실행하라는 의미입니다. -->\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write(" $(document).ready(function() {\r\n");
      out.write(" });\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.header .header_inner .top_logo {\r\n");
      out.write("	    width: 101px;\r\n");
      out.write("	    height: 43px;\r\n");
      out.write("	    background-image: url(\"resources/images/logo대충.png\");	\r\n");
      out.write("	    text-indent: -9999px;\r\n");
      out.write("	    margin-top: 7px;\r\n");
      out.write("	    display: block;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"header booking\">\r\n");
      out.write("        <div class=\"header_inner\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <a href=\"");
      out.print(request.getContextPath());
      out.write("\">\r\n");
      out.write("                <h1 class=\"top_logo\">캐럿 라인</h1>\r\n");
      out.write("            </a>\r\n");
      out.write("            <!--//  Logo -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Header Menu -->\r\n");
      out.write("            <div class=\"util_wrap\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- 유틸 메뉴 -->\r\n");
      out.write("                <div class=\"util_menu\">\r\n");
      out.write("                    <!-- 로그인 on / off 클래스 변경 -->\r\n");
      out.write("                    <!-- date-id layer_main1 / layer_main2 변경 -->\r\n");
      out.write("                    <a class=\"btn_login on\" href=\"javascript:logoutLayer();\">로그인 상태 상세보기</a>\r\n");
      out.write("                    <a class=\"btn_search\" href=\"#none\">검색</a>\r\n");
      out.write("                    <a class=\"btn_allmenu\" href=\"#none\">전체메뉴</a>\r\n");
      out.write("                    <!--// 로그인 전 -->\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- 유틸 메뉴 -->\r\n");
      out.write("            </div>\r\n");
      out.write("            <!--// Header Menu -->\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"wrap\">\r\n");
      out.write("    <!--// begin content -->\r\n");
      out.write("\r\n");
      out.write("<!-- Contnent -->\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("    <div class=\"content\" id=\"content\">\r\n");
      out.write("        <!-- 컨텐츠 영역 -->\r\n");
      out.write("\r\n");
      out.write("        <!-- Title & Step -->\r\n");
      out.write("        <div class=\"tit_booking_wrap\">\r\n");
      out.write("            <h2 class=\"pg_tit\">항공권예매</h2>\r\n");
      out.write("            <div class=\"step_booking\"> \r\n");
      out.write("                <ul class=\"bs4-order-tracking\"> \r\n");
      out.write("                    <li class=\"step active\">\r\n");
      out.write("                         <div><i class=\"fas fa-check\"></i></div> 1.여정검색 \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"step \"> \r\n");
      out.write("                        <div><i class=\"fas fa-check\"></i></div> 2.탑승자 정보 입력 \r\n");
      out.write("                    </li> \r\n");
      out.write("                    <li class=\"step \"> \r\n");
      out.write("                        <div><i class=\"fas fa-check\"></i></div> 3.부가서비스 \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"step \"> \r\n");
      out.write("                        <div><i class=\"fas fa-check\"></i></div> 4.선택내역 확인 및 규정동의 \r\n");
      out.write("                    </li>\r\n");
      out.write("                    <li class=\"step \"> \r\n");
      out.write("                        <div><i class=\"fas fa-check\"></i></div> 5.결제 \r\n");
      out.write("                    </li> \r\n");
      out.write("                    <li class=\"step \"> \r\n");
      out.write("                        <div><i class=\"fas fa-check\"></i></div> 6.예약완료 \r\n");
      out.write("                    </li>  			 \r\n");
      out.write("                    <br><br><br><br><br><br>\r\n");
      out.write("                </ul> \r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Title & Step -->\r\n");
      out.write("\r\n");
      out.write("        <!-- 여정검색  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- Input Booking -->\r\n");
      out.write("<div class=\"input_booking_wrap\">\r\n");
      out.write("<!-- 예약 탭 -->\r\n");
      out.write("<div class=\"booking_option\">\r\n");
      out.write("    <ul class=\"sel_section\">\r\n");
      out.write("        <li class=\"on\">\r\n");
      out.write("            <a href=\"#booking02\">   <!-- 편도 a태그 누르면 html내부링크 설정인 id가 booking02인 곳으로 이동 -->\r\n");
      out.write("                <input aria-hidden=\"true\" id=\"display_tripType_OW\" name=\"tripTypeButton\" tabindex=\"-1\" type=\"radio\" value=\"OW\">\r\n");
      out.write("                <label for=\"display_tripType_OW\">편도</label>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li>\r\n");
      out.write("            <a href=\"#booking01\">    <!-- 왕복 a태그 누르면 html내부링크 설정인 id가 booking01인 곳으로 이동-->\r\n");
      out.write("                <input aria-hidden=\"true\" id=\"display_tripType_RT\" name=\"tripTypeButton\" tabindex=\"-1\" type=\"radio\" value=\"RT\">\r\n");
      out.write("                <label for=\"display_tripType_RT\">왕복</label>\r\n");
      out.write("            </a>\r\n");
      out.write("        </li>\r\n");
      out.write("    </ul>\r\n");
      out.write("    \r\n");
      out.write("</div>\r\n");
      out.write("<!--// 예약 탭 -->\r\n");
      out.write("<!-- 왕복 -->\r\n");
      out.write("<div class=\"tab_cont fixed schedule_box\" id=\"booking01\" tabindex=\"0\" style=\"display: none;\">\r\n");
      out.write("    <div class=\"booking_input\">\r\n");
      out.write("        <ul class=\"booking_form\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"sel_route\">\r\n");
      out.write("                    <div class=\"input_wrap start\">\r\n");
      out.write("                        <label>출발지</label>\r\n");
      out.write("                        <input id=\"rt_start\" class=\"booking start focus_start1\" title=\"출발지 입력\" type=\"text\" placeholder=\"도시/공항\" value=\"\">\r\n");
      out.write("                        <a class=\"btn_pin focus_start2\" href=\"#none\" title=\"출발지 선택 레이어 열림\">출발지 선택</a>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                    <div id=\"route_departure_rt\" class=\"commonComponentLayer\" data-timestamp=\"1671066730313\" tabindex=\"0\" style=\"position: absolute; top: 90px; left: 48px; display: none;\">\r\n");
      out.write("\r\n");
      out.write("					<div id=\"start2\" class=\"layer_start2 second_start2 main_selec_start\">\r\n");
      out.write("							<div class=\"sel_area_list fix scroll mCustomScrollbar _mCS_3 mCS_no_scrollbar\">\r\n");
      out.write("							<div id=\"mCSB_3\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("							<div id=\"mCSB_3_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("								<ul>\r\n");
      out.write("										<li data-conticode=\"SKR\" class=\"contiList contiList_SKR\">\r\n");
      out.write("											<a class=\"sel_area\" href=\"#none\" >대한민국</a>\r\n");
      out.write("										</li>\r\n");
      out.write("									\r\n");
      out.write("										<li data-conticode=\"JAP\" class=\"contiList contiList_JAP\">\r\n");
      out.write("											<a class=\"sel_area\" href=\"#none\" >일본</a>\r\n");
      out.write("										</li>\r\n");
      out.write("									\r\n");
      out.write("										<li data-conticode=\"NEA\" class=\"contiList contiList_NEA\">\r\n");
      out.write("											<a class=\"sel_area\" href=\"#none\" >동북아시아</a>\r\n");
      out.write("										</li>\r\n");
      out.write("									\r\n");
      out.write("										<li data-conticode=\"SEA\" class=\"contiList contiList_SEA\">\r\n");
      out.write("											<a class=\"sel_area\" href=\"#none\" >동남아시아</a>\r\n");
      out.write("										</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("				\r\n");
      out.write("							</div>\r\n");
      out.write("<!-- 							<div id=\"mCSB_3_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_3_scrollbar mCS-light mCSB_scrollTools_vertical\" style=\"display: none;\"> -->\r\n");
      out.write("<!-- 								<div class=\"mCSB_draggerContainer\"> -->\r\n");
      out.write("<!-- 									<div id=\"mCSB_3_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 30px; height: 0px; top: 0px;\"> -->\r\n");
      out.write("<!-- 										<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div> -->\r\n");
      out.write("<!-- 									</div> -->\r\n");
      out.write("<!-- 									<div class=\"mCSB_draggerRail\"></div> -->\r\n");
      out.write("<!-- 								</div> -->\r\n");
      out.write("<!-- 							</div>  -->\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("							\r\n");
      out.write("							<!--// 지역선택 -->\r\n");
      out.write("				\r\n");
      out.write("							\r\n");
      out.write("							<!-- 취항지 -->\r\n");
      out.write("							<div class=\"sel_route_list type2 scroll mCustomScrollbar _mCS_4 mCS_no_scrollbar\">\r\n");
      out.write("							<div id=\"mCSB_4\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("								<div id=\"mCSB_4_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("				\r\n");
      out.write("									<div class=\"airportList_Dep scroll\" style=\"display: block;\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							</div>\r\n");
      out.write("							<!--/ 취향지 -->\r\n");
      out.write("					<div><button id=\"close_btn\" class=\"close_airport_btn\">닫기</button></div>	\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				\r\n");
      out.write("	\r\n");
      out.write("                    <!-- //공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                   \r\n");
      out.write("			\r\n");
      out.write("                    <a class=\"btn_change\" href=\"#none\">출발지/도착지 바꾸기</a>\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"input_wrap end\">\r\n");
      out.write("                        <label>도착지</label>\r\n");
      out.write("                        <input id=\"rt_finish\" class=\"booking end focus_end1\" title=\"도착지 선택\" type=\"text\" placeholder=\"도시/공항\" value=\"\">\r\n");
      out.write("                        <a class=\"btn_pin end focus_end2\" href=\"#none\">도착지 선택</a>\r\n");
      out.write("                       \r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                    <div id=\"route_arrival_rt\" class=\"commonComponentLayer\" data-timestamp=\"1672144106694\" tabindex=\"0\" style=\"position: absolute; top: 90px; left: 48px; display: none;\">\r\n");
      out.write("						<div id=\"start2\" class=\"layer_start2 main_selec_start if437\">\r\n");
      out.write("								<!-- 지역선택 -->\r\n");
      out.write("								<div class=\"sel_area_list type2 scroll mCustomScrollbar _mCS_5 mCS_no_scrollbar\">\r\n");
      out.write("								<div id=\"mCSB_5\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("								<div id=\"mCSB_5_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("									<ul>\r\n");
      out.write("					                        <li data-conticode=\"SKR\" class=\"contiList contiList_SKR\">\r\n");
      out.write("					                            <a class=\"sel_area\" href=\"#none\">대한민국</a>\r\n");
      out.write("					                        </li>\r\n");
      out.write("					\r\n");
      out.write("					                        <li data-conticode=\"JAP\" class=\"contiList contiList_JAP\">\r\n");
      out.write("												<a class=\"sel_area\" href=\"#none\">일본</a>\r\n");
      out.write("											</li>\r\n");
      out.write("										\r\n");
      out.write("											<li data-conticode=\"NEA\" class=\"contiList contiList_NEA\">\r\n");
      out.write("												<a class=\"sel_area\" href=\"#none\">동북아시아</a>\r\n");
      out.write("											</li>\r\n");
      out.write("										\r\n");
      out.write("											<li data-conticode=\"SEA\" class=\"contiList contiList_SEA\">\r\n");
      out.write("												<a class=\"sel_area\" href=\"#none\">동남아시아</a>\r\n");
      out.write("											</li>					\r\n");
      out.write("					\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								\r\n");
      out.write("								</div>\r\n");
      out.write("								</div>\r\n");
      out.write("								<!--// 지역선택 -->\r\n");
      out.write("					\r\n");
      out.write("					\r\n");
      out.write("								<!-- 취향지 -->\r\n");
      out.write("								<div class=\"sel_route_list type2 scroll mCustomScrollbar _mCS_6 mCS_no_scrollbar\">\r\n");
      out.write("								<div id=\"mCSB_6\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("									<div id=\"mCSB_6_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("											<div class=\"airportList_Arr scroll\" style=\"display: block;\">\r\n");
      out.write("												<ul>\r\n");
      out.write("												</ul>\r\n");
      out.write("											</div>\r\n");
      out.write("									</div>\r\n");
      out.write("						        </div>\r\n");
      out.write("						        </div>\r\n");
      out.write("								<!--// 취향지 -->\r\n");
      out.write("						<div><button id=\"close_btn\" class=\"close_airport_btn\">닫기</button></div>			\r\n");
      out.write("					</div>\r\n");
      out.write("                    <!-- //공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"input_wrap date rt\">\r\n");
      out.write("                    <label>탑승일</label>\r\n");
      out.write("                    <input class=\"booking date focus_date1\" id=\"lostFlightDate1_1\" placeholder=\"YYYY-MM-DD\" readonly=\"readonly\" title=\"출발일 선택\" type=\"text\" value=\"\">\r\n");
      out.write("                    <span class=\"space\">~</span>\r\n");
      out.write("                    <input class=\"booking date focus_date2\" id=\"lostFlightDate1_2\" placeholder=\"YYYY-MM-DD\" readonly=\"readonly\" title=\"도착일 선택\" type=\"text\" value=\"\">\r\n");
      out.write("                    <a class=\"btn_date focus_date3\" href=\"#none\">날짜선택</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("<!--     <div id=\"calOpen\" style=\"display:none;\"> -->\r\n");
      out.write("<!--         <section class=\"ftco-section\"> -->\r\n");
      out.write("<!-- 		<div class=\"calContainer\" > -->\r\n");
      out.write("<!-- 			<div class=\"calRow justify-content-center\"> -->\r\n");
      out.write("<!-- 				<div class=\"col-md-6 text-center mb-5\"> -->\r\n");
      out.write("<!-- 					<h2 class=\"heading-section\">예매 일정 선택</h2> -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("<!-- 			<div class=\"calRow\"> -->\r\n");
      out.write("<!-- 				<div class=\"col-md-12\"> -->\r\n");
      out.write("<!-- 					<div class=\"calendar-section\"> -->\r\n");
      out.write("<!-- 		        <div class=\"calRow no-gutters\"> -->\r\n");
      out.write("<!-- 		          <div class=\"col-md-6\"> -->\r\n");
      out.write("<!-- ​ -->\r\n");
      out.write("<!-- 					달력 2개 중 첫번째 달력 -->\r\n");
      out.write("<!-- 		            <div class=\"calendar calendar-first no-gutters\" id=\"calendar_first\">	cal1 -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_header\">	calHeader1 -->\r\n");
      out.write("<!-- 		                <button class=\"switch-month switch-left\"> -->\r\n");
      out.write("<!-- 		                  <i class=\"fa fa-chevron-left\"></i> -->\r\n");
      out.write("<!-- 		                </button> -->\r\n");
      out.write("<!-- 		                <h2></h2> -->\r\n");
      out.write("<!-- 		                <button class=\"switch-month switch-right\"> -->\r\n");
      out.write("<!-- 		                  <i class=\"fa fa-chevron-right\"></i> -->\r\n");
      out.write("<!-- 		                </button> -->\r\n");
      out.write("<!-- 		              </div> -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_weekdays\"></div>	weekline1 -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_content\"></div>	datesBody1 -->\r\n");
      out.write("<!-- 		            </div> -->\r\n");
      out.write("<!-- ​ -->\r\n");
      out.write("<!-- 		          </div> -->\r\n");
      out.write("<!-- 		          <div class=\"col-md-6\"> -->\r\n");
      out.write("<!-- 					달력 2개 중 두번째 달력	 -->\r\n");
      out.write("<!-- 		            <div class=\"calendar calendar-second no-gutters\" id=\"calendar_second\">	cal2 -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_header\">	calHeader2 -->\r\n");
      out.write("<!-- 		                <button class=\"switch-month switch-left\"> -->\r\n");
      out.write("<!-- 		                  <i class=\"fa fa-chevron-left\"></i> -->\r\n");
      out.write("<!-- 		                </button> -->\r\n");
      out.write("<!-- 		                <h2></h2> -->\r\n");
      out.write("<!-- 		                <button class=\"switch-month switch-right\"> -->\r\n");
      out.write("<!-- 		                  <i class=\"fa fa-chevron-right\"></i> -->\r\n");
      out.write("<!-- 		                </button> -->\r\n");
      out.write("<!-- 		              </div> -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_weekdays\"></div>	weekline2 -->\r\n");
      out.write("<!-- 		              <div class=\"calendar_content\"></div>	datesBody2 -->\r\n");
      out.write("<!-- 		            </div>             -->\r\n");
      out.write("<!-- ​ -->\r\n");
      out.write("<!-- 		          </div> -->\r\n");
      out.write("<!-- ​ -->\r\n");
      out.write("<!-- 		        </div> End Row -->\r\n");
      out.write("		            \r\n");
      out.write("<!-- 		      </div> End Calendar -->\r\n");
      out.write("<!-- 				</div> -->\r\n");
      out.write("<!-- 			</div> -->\r\n");
      out.write("<!-- 		</div> -->\r\n");
      out.write("<!-- 	</section> -->\r\n");
      out.write("<!-- </div> -->\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 왕복 -->\r\n");
      out.write("<!-- 편도 -->\r\n");
      out.write("<div class=\"tab_cont fixed schedule_box\" id=\"booking02\" tabindex=\"-1\" style=\"display: block;\">\r\n");
      out.write("    <div class=\"booking_input\">\r\n");
      out.write("        <ul class=\"booking_form\">\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"sel_route\">\r\n");
      out.write("                    <div class=\"input_wrap start\">\r\n");
      out.write("                        <label>출발지</label>\r\n");
      out.write("                        <input id=\"ow_start\" class=\"booking start focus_start1\" title=\"출발지 입력\" type=\"text\" value=\"\" placeholder=\"도시/공항\">\r\n");
      out.write("                        <a class=\"btn_pin focus_start2\" href=\"#none\" title=\"출발지 선택 레이어 열림\">출발지 선택</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                    <div id=\"route_departure_ow\" class=\"commonComponentLayer\" data-timestamp=\"1671066730313\" tabindex=\"0\" style=\"position: absolute; top: 90px; left: 48px; display: none;\">\r\n");
      out.write("					<div id=\"start2\" class=\"layer_start2 second_start2 main_selec_start\">\r\n");
      out.write("						<div class=\"layer_cont\">\r\n");
      out.write("							<div class=\"sel_area_list fix scroll mCustomScrollbar _mCS_11 mCS_no_scrollbar\">\r\n");
      out.write("							<div id=\"mCSB_11\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("							<div id=\"mCSB_11_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("								<ul>\r\n");
      out.write("									<li data-conticode=\"SKR\" class=\"contiList contiList_SKR\">\r\n");
      out.write("										<a class=\"sel_area\" href=\"#none\" >대한민국</a>\r\n");
      out.write("									</li>\r\n");
      out.write("								\r\n");
      out.write("									<li data-conticode=\"JAP\" class=\"contiList contiList_JAP\">\r\n");
      out.write("										<a class=\"sel_area\" href=\"#none\" >일본</a>\r\n");
      out.write("									</li>\r\n");
      out.write("								\r\n");
      out.write("									<li data-conticode=\"NEA\" class=\"contiList contiList_NEA\">\r\n");
      out.write("										<a class=\"sel_area\" href=\"#none\" >동북아시아</a>\r\n");
      out.write("									</li>\r\n");
      out.write("								\r\n");
      out.write("									<li data-conticode=\"SEA\" class=\"contiList contiList_SEA\">\r\n");
      out.write("										<a class=\"sel_area\" href=\"#none\" >동남아시아</a>\r\n");
      out.write("									</li>\r\n");
      out.write("								</ul>\r\n");
      out.write("				\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"mCSB_11_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_11_scrollbar mCS-light mCSB_scrollTools_vertical\" style=\"display: none;\">\r\n");
      out.write("							<div class=\"mCSB_draggerContainer\"><div id=\"mCSB_11_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 30px; height: 0px; top: 0px;\">\r\n");
      out.write("							<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div></div><div class=\"mCSB_draggerRail\"></div></div></div></div></div>\r\n");
      out.write("							<!--// 지역선택 -->\r\n");
      out.write("				\r\n");
      out.write("							\r\n");
      out.write("							<!-- 취항지 -->\r\n");
      out.write("							<div class=\"sel_route_list type2 scroll mCustomScrollbar _mCS_12 mCS_no_scrollbar\">\r\n");
      out.write("							<div id=\"mCSB_12\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("							<div id=\"mCSB_12_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("				\r\n");
      out.write("									<div class=\"airportList_Dep scroll\" style=\"display: block;\">\r\n");
      out.write("										<ul>\r\n");
      out.write("											\r\n");
      out.write("										</ul>\r\n");
      out.write("									</div>\r\n");
      out.write("								\r\n");
      out.write("								\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"mCSB_12_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_12_scrollbar mCS-light mCSB_scrollTools_vertical\" style=\"display: none;\">\r\n");
      out.write("							<div class=\"mCSB_draggerContainer\"><div id=\"mCSB_12_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 30px; height: 0px; top: 0px;\">\r\n");
      out.write("							<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div></div><div class=\"mCSB_draggerRail\"></div></div></div></div></div>\r\n");
      out.write("							<!--/ 취향지 -->\r\n");
      out.write("							<div><button id=\"close_btn\" class=\"close_airport_btn\">닫기</button></div>	\r\n");
      out.write("						</div>\r\n");
      out.write("						\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!--// Input Hover 시 -->\r\n");
      out.write("	\r\n");
      out.write("                    <!-- //공항 선택 div 들어갈 자리 -->\r\n");
      out.write("                    \r\n");
      out.write("                    <a class=\"btn_change\" href=\"#none\">출발지/도착지 바꾸기</a>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"input_wrap end\">\r\n");
      out.write("                        <label>도착지</label>\r\n");
      out.write("                        <input id=\"ow_finish\" class=\"booking end focus_end1\" title=\"도착지 입력\" type=\"text\" value=\"\" placeholder=\"도시/공항\">\r\n");
      out.write("                        <a class=\"btn_pin end focus_end2\" href=\"#none\" >도착지 선택</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <!-- 공항 선택 div 들어갈 자리 -->\r\n");
      out.write("					<div id=\"route_arrival_ow\" class=\"commonComponentLayer\" data-timestamp=\"1672153053390\" tabindex=\"0\" style=\"position: absolute; top: 90px; left: 48px; display:none;\">\r\n");
      out.write("					    <div id=\"start2\" class=\"layer_start2 main_selec_start if437\">\r\n");
      out.write("							<div class=\"layer_cont\">\r\n");
      out.write("								<div class=\"sel_area_list type2 scroll mCustomScrollbar _mCS_7 mCS_no_scrollbar\">\r\n");
      out.write("								<div id=\"mCSB_7\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("								<div id=\"mCSB_7_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("									<ul>\r\n");
      out.write(" 										\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"mCSB_7_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_7_scrollbar mCS-light mCSB_scrollTools_vertical\" style=\"display: none;\">\r\n");
      out.write("								<div class=\"mCSB_draggerContainer\">\r\n");
      out.write("								<div id=\"mCSB_7_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 30px; height: 0px; top: 0px;\">\r\n");
      out.write("								<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div></div><div class=\"mCSB_draggerRail\"></div></div></div>\r\n");
      out.write("								</div></div>\r\n");
      out.write("								<!--// 지역선택 -->\r\n");
      out.write("					\r\n");
      out.write("								\r\n");
      out.write("								<!-- 취향지 -->\r\n");
      out.write("								<div class=\"sel_route_list type2 scroll mCustomScrollbar _mCS_8 mCS_no_scrollbar\">\r\n");
      out.write("								<div id=\"mCSB_8\" class=\"mCustomScrollBox mCS-light mCSB_vertical mCSB_inside\" tabindex=\"0\" style=\"max-height: none;\">\r\n");
      out.write("								<div id=\"mCSB_8_container\" class=\"mCSB_container mCS_y_hidden mCS_no_scrollbar_y\" style=\"position:relative; top:0; left:0;\" dir=\"ltr\">\r\n");
      out.write("					\r\n");
      out.write("										<div class=\"airportList_Arr scroll\" style=\"display: block;\">\r\n");
      out.write("											<ul>\r\n");
      out.write("											</ul>\r\n");
      out.write("										</div>\r\n");
      out.write("					\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"mCSB_8_scrollbar_vertical\" class=\"mCSB_scrollTools mCSB_8_scrollbar mCS-light mCSB_scrollTools_vertical\" style=\"display: none;\">\r\n");
      out.write("								<div class=\"mCSB_draggerContainer\">\r\n");
      out.write("								<div id=\"mCSB_8_dragger_vertical\" class=\"mCSB_dragger\" style=\"position: absolute; min-height: 30px; height: 0px; top: 0px;\">\r\n");
      out.write("								<div class=\"mCSB_dragger_bar\" style=\"line-height: 30px;\"></div></div><div class=\"mCSB_draggerRail\"></div></div></div></div></div>\r\n");
      out.write("								<!--/ 취향지 -->\r\n");
      out.write("								<div><button id=\"close_btn\" class=\"close_airport_btn\">닫기</button></div>	\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li>\r\n");
      out.write("                <div class=\"input_wrap date ow\">\r\n");
      out.write("                    <label>탑승일</label>\r\n");
      out.write("                    <input class=\"booking date focus_date1\" id=\"lostFlightDate2_1\" placeholder=\"YYYY-MM-DD\" readonly=\"readonly\" title=\"출발일 입력\" type=\"text\" value=\"\" >\r\n");
      out.write("                    <a class=\"btn_date focus_date3\" href=\"#none\" title=\"출발일 선택 레이어 열림\">출발일 선택</a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("     <div id=\"calOpen2\" style=\"display:none;\">\r\n");
      out.write("        <section class=\"ftco-section\">\r\n");
      out.write("		<div class=\"calContainer\" >\r\n");
      out.write("			<div class=\"calRow justify-content-center\">\r\n");
      out.write("				<div class=\"col-md-6 text-center mb-5\">\r\n");
      out.write("					<h2 class=\"heading-section\">예매 일정 선택</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"calRow\">\r\n");
      out.write("				<div class=\"col-md-12\">\r\n");
      out.write("					<div class=\"calendar-section\">\r\n");
      out.write("		        <div class=\"calRow no-gutters\">\r\n");
      out.write("		          <div class=\"col-md-6\">\r\n");
      out.write("​\r\n");
      out.write("					<!-- 달력 2개 중 첫번째 달력 -->\r\n");
      out.write("		            <div class=\"calendar calendar-first no-gutters\" id=\"calendar_first1\">	<!-- cal1 -->\r\n");
      out.write("		              <div class=\"calendar_header\">	<!-- calHeader1 -->\r\n");
      out.write("		                <button class=\"switch-month switch-left\">\r\n");
      out.write("		                  <i class=\"fa fa-chevron-left\"></i>\r\n");
      out.write("		                </button>\r\n");
      out.write("		                <h2></h2>\r\n");
      out.write("		                <button class=\"switch-month switch-right\">\r\n");
      out.write("		                  <i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("		                </button>\r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"calendar_weekdays\"></div>	<!-- weekline1 -->\r\n");
      out.write("		              <div class=\"calendar_content\"></div>	<!-- datesBody1 -->\r\n");
      out.write("		            </div>\r\n");
      out.write("​\r\n");
      out.write("		          </div>\r\n");
      out.write("		          <div class=\"col-md-6\">\r\n");
      out.write("					<!-- 달력 2개 중 두번째 달력 -->	\r\n");
      out.write("		            <div class=\"calendar calendar-second no-gutters\" id=\"calendar_second2\">	<!-- cal2 -->\r\n");
      out.write("		              <div class=\"calendar_header\">	<!-- calHeader2 -->\r\n");
      out.write("		                <button class=\"switch-month switch-left\">\r\n");
      out.write("		                  <i class=\"fa fa-chevron-left\"></i>\r\n");
      out.write("		                </button>\r\n");
      out.write("		                <h2></h2>\r\n");
      out.write("		                <button class=\"switch-month switch-right\">\r\n");
      out.write("		                  <i class=\"fa fa-chevron-right\"></i>\r\n");
      out.write("		                </button>\r\n");
      out.write("		              </div>\r\n");
      out.write("		              <div class=\"calendar_weekdays\"></div>	<!-- weekline2 -->\r\n");
      out.write("		              <div class=\"calendar_content\"></div>	<!-- datesBody2 -->\r\n");
      out.write("		            </div>            \r\n");
      out.write("​\r\n");
      out.write("		          </div>\r\n");
      out.write("​\r\n");
      out.write("		        </div> <!-- End Row -->\r\n");
      out.write("		            \r\n");
      out.write("		      </div> <!-- End Calendar -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- 편도 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--// Tab 컨텐츠 -->\r\n");
      out.write("\r\n");
      out.write("<!-- 인원수 입력 -->\r\n");
      out.write("<div class=\"pax booking_input section_passenger\">\r\n");
      out.write("    <ul class=\"booking_form\">\r\n");
      out.write("        <li>\r\n");
      out.write("            <div class=\"input_wrap passenger focus\">\r\n");
      out.write("                <!-- 성인 -->\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>\r\n");
      out.write("                        <label for=\"adult\">성인</label>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd class=\"sel_passenger\">\r\n");
      out.write("                        <a class=\"adult btn_minus\" href=\"#none\"></a>\r\n");
      out.write("                        <input class=\"booking passenger ADULT\" data-div=\"ADULT\" id=\"adult\" title=\"성인 인원수\" type=\"text\" value=\"1\" readonly>\r\n");
      out.write("                        <a class=\"adult btn_plus\" href=\"#none\" ></a>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <!--// 성인 -->\r\n");
      out.write("                <!-- 소아 -->\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>\r\n");
      out.write("                        <label for=\"kid\">\r\n");
      out.write("                                소아\r\n");
      out.write("                            <a class=\"btn_tooltip gray kid\" href=\"#none\">\r\n");
      out.write("                                <span class=\"blind\">툴팁</span>\r\n");
      out.write("                                <div class=\"tooltip_layer kid\" style=\"display: none;\">\r\n");
      out.write("                                    <div class=\"tooltip_tit\">\r\n");
      out.write("                                        <img alt=\"\" src=\"https://contents-image.twayair.com/homepage/images/ico/ico_kid.png\">\r\n");
      out.write("                                        <h5>소아기준</h5>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tooltip_cont\">\r\n");
      out.write("                                        <dl>\r\n");
      out.write("                                            <dt>국내선</dt>\r\n");
      out.write("                                            <dd>만 2세~<span class=\"red\">13세</span> 미만</dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl>\r\n");
      out.write("                                            <dt>국제선</dt>\r\n");
      out.write("                                            <dd>만 2세~<span class=\"red\">12세</span> 미만</dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <ul class=\"info\"><li>※ 소아/유아 기준</li>\r\n");
      out.write("<li>&nbsp; &nbsp; - 국내선 : 각 항공편의 탑승일 기준</li>\r\n");
      out.write("<li>&nbsp; &nbsp; - 국제선 : 최초 출발일 기준</li>\r\n");
      out.write("<li>※ 탑승 수속 시 생년월일 확인 가능한 서류 지참 필수</li></ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd class=\"sel_passenger\">\r\n");
      out.write("                        <a class=\"kid btn_minus\" href=\"#none\">소아 인원감소</a>\r\n");
      out.write("                        <input class=\"booking passenger CHILD\" data-div=\"CHILD\" id=\"kid\" title=\"소아 인원수\" type=\"text\" value=\"0\" readonly>\r\n");
      out.write("                        <a class=\"kid btn_plus\" href=\"#none\">소아 인원증가</a>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <!--// 소아 -->\r\n");
      out.write("                <!-- 유아 -->\r\n");
      out.write("                <dl>\r\n");
      out.write("                    <dt>\r\n");
      out.write("                        <label for=\"baby\">\r\n");
      out.write("                                유아\r\n");
      out.write("                            <a class=\"btn_tooltip gray baby\" href=\"#none\">\r\n");
      out.write("                                <span class=\"blind\">툴팁</span>\r\n");
      out.write("                                <div class=\"tooltip_layer baby\" style=\"display: none;\">\r\n");
      out.write("                                    <div class=\"tooltip_tit\">\r\n");
      out.write("                                        <img alt=\"\" src=\"https://contents-image.twayair.com/homepage/images/ico/ico_baby.png\">\r\n");
      out.write("                                        <h5>유아기준</h5>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"tooltip_cont\">\r\n");
      out.write("                                        <dl>\r\n");
      out.write("                                            <dt>국내선</dt>\r\n");
      out.write("                                            <dd>생후 <span class=\"red\">7일</span>~ 만 2세 미만</dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <dl>\r\n");
      out.write("                                            <dt>국제선</dt>\r\n");
      out.write("                                            <dd>생후 <span class=\"red\">14일</span>~ 만 2세 미만</dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                        <ul class=\"info\"><li>※ 소아/유아 기준</li>\r\n");
      out.write("<li>&nbsp; &nbsp; - 국내선 : 각 항공편의 탑승일 기준</li>\r\n");
      out.write("<li>&nbsp; &nbsp; - 국제선 : 최초 출발일 기준</li>\r\n");
      out.write("<li>※ 탑승 수속 시 생년월일 확인 가능한 서류 지참 필수</li></ul>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </dt>\r\n");
      out.write("                    <dd class=\"sel_passenger\">\r\n");
      out.write("                        <a class=\"baby btn_minus\" href=\"#none\">유아 인원감소</a>\r\n");
      out.write("                        <input class=\"booking passenger INFANT\" data-div=\"INFANT\" id=\"baby\" onkeyup=\"onlyNumReplace(this, 0);\" title=\"유아 인원수\" type=\"text\" value=\"0\" readonly>\r\n");
      out.write("                        <a class=\"baby btn_plus\" href=\"#none\">유아 인원증가</a>\r\n");
      out.write("                    </dd>\r\n");
      out.write("                </dl>\r\n");
      out.write("                <!--// 유아 -->\r\n");
      out.write("            </div>\r\n");
      out.write("        </li>\r\n");
      out.write("       \r\n");
      out.write("    </ul>\r\n");
      out.write("</div>\r\n");
      out.write("<!--// 인원수 입력 -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--// Input Booking -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!--// 컨텐츠 영역 -->\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("        <!--script단-->\r\n");
      out.write("        <!--script단-->\r\n");
      out.write("\r\n");
      out.write("        <!-- Button -->\r\n");
      out.write("        <div class=\"btn_wrap\">\r\n");
      out.write("            <button class=\"btn_large red\" onclick=\"bookingBtn();\">예매하기</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!--// Button -->\r\n");
      out.write("</div>\r\n");
      out.write("<!--// Contnent -->\r\n");
      out.write("\r\n");
      out.write("    <!--// end content -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- boonkigPage1-1 script -->\r\n");
      out.write("<script charset=\"utf-8\" src=\"resources/js/bookingPage1-1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("function bookingBtn(){\r\n");
      out.write("	\r\n");
      out.write("	$caDepartureDate = $('#lostFlightDate2_1').val();\r\n");
      out.write("	\r\n");
      out.write("	console.log($caDepartureDate);\r\n");
      out.write("	\r\n");
      out.write("  	var params = {//전송할 데이터 객체 params\r\n");
      out.write("  		caKind : \"OW\",\r\n");
      out.write("		caDepartureAirport :$caDepartureAirport,\r\n");
      out.write("		caArrivalAirport : $caArrivalAirport,\r\n");
      out.write("		caDepCity : $caDepCity,\r\n");
      out.write("		caArrCity : $caArrCity,\r\n");
      out.write("		caDepartureDate : $caDepartureDate,\r\n");
      out.write("		caConti : $caConti,\r\n");
      out.write("		caAdult : $caAdult,\r\n");
      out.write("		caChild : $caChild,\r\n");
      out.write("		caBaby : $caBaby\r\n");
      out.write("	};\r\n");
      out.write("	\r\n");
      out.write("  	\r\n");
      out.write("    var form = document.createElement('form');        //form 생성\r\n");
      out.write("    \r\n");
      out.write("    form.setAttribute('method', 'post');              //POST 방식\r\n");
      out.write("    form.setAttribute('action', 'bookingOW.re');	      //데이터를 전송할 url\r\n");
      out.write("    document.charset = \"UTF-8\";                       //인코딩\r\n");
      out.write("//     document.form.acceptCharset = \"UTF-8\"\r\n");
      out.write("	\r\n");
      out.write("    for (var key in params) {	// key, value로 이루어진 객체 params\r\n");
      out.write("        var hiddenField = document.createElement('input');\r\n");
      out.write("        hiddenField.setAttribute('type', 'hidden');\r\n");
      out.write("        hiddenField.setAttribute('name', key);\r\n");
      out.write("        hiddenField.setAttribute('value', params[key]);\r\n");
      out.write("        form.appendChild(hiddenField);\r\n");
      out.write("    }\r\n");
      out.write("    document.body.appendChild(form);\r\n");
      out.write("    \r\n");
      out.write("    form.submit();	// 전송\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- calendar script -->\r\n");
      out.write("<!-- <script src=\"resources/js/calRt.js\"></script> -->\r\n");
      out.write("<script src=\"resources/js/calOw.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
