/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-01-25 12:05:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.booking;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bookingPage2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1674643862407L));
    _jspx_dependants.put("jar:file:/D:/final-project(LAST)/carrotline/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>CARROT LINE Booking</title>\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/reset.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/common/header.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"");
      out.print(request.getContextPath());
      out.write("/resources/css/booking/bookingWrite.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/a076d05399.js'></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<script src='https://kit.fontawesome.com/77ad8525ff.js' crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("	.bs4-order-tracking{margin-bottom: 30px;overflow: hidden; color: #878788;padding-left: 0px;margin-top: 30px} \r\n");
      out.write("	.bs4-order-tracking li{list-style-type: none;font-size: 13px;width: 15%;   float: left;position: relative;font-weight: 400;color: #878788;text-align: center}\r\n");
      out.write("	.bs4-order-tracking li:first-child:before{margin-left: 15px !important;padding-left: 11px !important;text-align : left !important}\r\n");
      out.write("	.bs4-order-tracking li:last-child:before{margin-right: 5px !important;padding-right: 11px !important;text-align : right !important}\r\n");
      out.write("	.bs4-order-tracking li>div{color: #fff;width: 29px; height: 29px; text-align: center; line-height: 29px;display: block;font-size: 12px;background: #878788;border-radius: 50%; margin: auto;}\r\n");
      out.write("	.bs4-order-tracking li>div>i{margin-top: 10px;}\r\n");
      out.write("	.bs4-order-tracking li:after{content: '';width: 150%;height: 2px;background: #878788;position: absolute;left: 0%;right: 0%;top: 15px;z-index: -1}\r\n");
      out.write("	.bs4-order-tracking li:first-child:after{left: 50%}\r\n");
      out.write("	.bs4-order-tracking li:last-child:after{left: 0%!important;width: 0% !important}\r\n");
      out.write("	.bs4-order-tracking li.active{font-weight: bold;color: #dc3545}\r\n");
      out.write("	.bs4-order-tracking li.active>div{background: #da5c3d}\r\n");
      out.write("	.bs4-order-tracking li.active:after{background: #da5c3d}\r\n");
      out.write("	.card-timeline{background-color: #fff;z-index: 0}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"], input[type=\"radio\"]{\r\n");
      out.write("	display: none;\r\n");
      out.write("}\r\n");
      out.write("	input[type=\"radio\"]:checked + label {\r\n");
      out.write("	    background-position: 0 -20px;}\r\n");
      out.write("	input[type=\"radio\"] + label {\r\n");
      out.write("	    height: 20px;\r\n");
      out.write("	    padding: 0 30px;\r\n");
      out.write("	    background: url(");
      out.print(request.getContextPath() );
      out.write("/resources/images/bg_radio.png) no-repeat;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    color: #222;\r\n");
      out.write("	    vertical-align: middle;\r\n");
      out.write("	    line-height: 18px;}\r\n");
      out.write("	/* checkbox */\r\n");
      out.write("	input[type=\"checkbox\"]:checked + label {\r\n");
      out.write("	    background: url(");
      out.print(request.getContextPath() );
      out.write("/resources/images/bg_checkbox_check.png) no-repeat;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	input[type=\"checkbox\"] + label {\r\n");
      out.write("	    min-height: 20px;\r\n");
      out.write("	    padding: 0 40px 0 30px;\r\n");
      out.write("	    background: url(");
      out.print(request.getContextPath() );
      out.write("/resources/images/bg_checkbox_default.png) no-repeat;\r\n");
      out.write("	    font-size: 16px;\r\n");
      out.write("	    color: #222;\r\n");
      out.write("	    vertical-align: middle;\r\n");
      out.write("	    line-height: 18px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	table .bth{\r\n");
      out.write("		background-color: #EB8401;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	#btn{\r\n");
      out.write("		background-color: #EB8401;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	/* checkbox 끝  */\r\n");
      out.write("	\r\n");
      out.write("	select {\r\n");
      out.write("		height: 46px;\r\n");
      out.write("		padding: 0 45px 0 15px;\r\n");
      out.write("		margin-right: 10px;\r\n");
      out.write("		border: 1px solid #f3f3f3;\r\n");
      out.write("		border-bottom: 1px solid #ddd;\r\n");
      out.write("		background: #f3f3f3 url('");
      out.print(request.getContextPath() );
      out.write("/resources/images/bg_select_arrow.png') no-repeat\r\n");
      out.write("			right 13px top 50%;\r\n");
      out.write("		background-size: 12px 8px;\r\n");
      out.write("		color: #222;\r\n");
      out.write("		vertical-align: middle;\r\n");
      out.write("		-webkit-appearance:none;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/bookingPage3.re\" method=\"post\">\r\n");
      out.write("<section>\r\n");
      out.write("\r\n");
      out.write("	<!--넘어가는 과정 추가 -->\r\n");
      out.write("	<div class=\"card card-timeline px-2 border-none\">\r\n");
      out.write("		<ul class=\"bs4-order-tracking\"> \r\n");
      out.write("			<li class=\"step active\">\r\n");
      out.write("				 <div><i class=\"fas fa-check\"></i></div> 1.여정검색 </li>\r\n");
      out.write("			<li class=\"step active\"> \r\n");
      out.write("				<div><i class=\"fas fa-check\"></i></div> 2.탑승자 정보 입력 </li> \r\n");
      out.write("			<li class=\"step \"> \r\n");
      out.write("				<div><i class=\"fas fa-check\"></i></div> 3.부가서비스 </li>\r\n");
      out.write("			<li class=\"step \"> \r\n");
      out.write("				<div><i class=\"fas fa-check\"></i></div> 4.선택내역 확인 및 규정동의 </li>\r\n");
      out.write("			<li class=\"step \"> \r\n");
      out.write("				<div><i class=\"fas fa-check\"></i></div> 5.결제 </li> \r\n");
      out.write("			<li class=\"step \"> \r\n");
      out.write("				<div><i class=\"fas fa-check\"></i></div> 6.예약완료 </li>  			 \r\n");
      out.write("		</ul> \r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"title\">탑승자 정보</div>\r\n");
      out.write("	<div id=\"tmsg\" align=\"center\">신분증에 기재된 이름,생년월일 등을 작성하세요.</div>\r\n");
      out.write("	\r\n");
      out.write("<div> \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- %%%%%%%% -->\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("<div id=\"title\">예약자 연락처 정보</div>\r\n");
      out.write("<div id=\"tmsg\">예약정보수신 연락처에 작성하신 이메일로 구매 결과와 여정안내서를 전송해드립니다.</div>\r\n");
      out.write("\r\n");
      out.write("<table style=\"margin-left: 111px;\">\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"bth\">이메일</td>\r\n");
      out.write("<td class=\"btb\">\r\n");
      out.write("<input type=\"email\" name=\"resEmail\" class=\"hannaName\" id=\"re\" >\r\n");
      out.write("<input type=\"checkbox\" name=\"resECheck\" id=\"resECheck\" checked=\"checked\">\r\n");
      out.write("<label for=\"resECheck\">이메일 항공권 수신동의</label>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("\r\n");
      out.write("<tr>\r\n");
      out.write("<td class=\"bth\">전화번호</td>\r\n");
      out.write("<td class=\"btb\">\r\n");
      out.write("<input type=\"text\" name=\"resPhone\" class=\"hannaName\" id=\"rp\" maxlength=\"13\">\r\n");
      out.write("<input type=\"checkbox\" name=\"resPCheck\" id=\"resPCheck\" checked=\"checked\">\r\n");
      out.write("<label for=\"resPCheck\">SMS 수신 동의</label>\r\n");
      out.write("</td>\r\n");
      out.write("</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<hr>\r\n");
      out.write("\r\n");
      out.write("<div class=\"gray_box\" id=\"rev_dom_notice\">\r\n");
      out.write("	<h5>유의사항</h5>\r\n");
      out.write("	<ul class=\"list_type2\">\r\n");
      out.write("		<li>예약 클래스에 따라 마일리지 적립이 불가하거나 적립률이 상이할 수 있으며, 실제 운항하는 항공사의 기준에 따라 적립이 이루어집니다.</li>\r\n");
      out.write("		<li>해당 항공사 마일리지 적립 규정상 적립이 불가한 경우에는 회원번호를 입력하셔도 적립이 되지 않습니다.</li>\r\n");
      out.write("		<li>현재 시스템 문제로, 숫자와 영문을 조합한 이메일 주소만 사용 가능합니다.</li>\r\n");
      out.write("	</ul>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</section>\r\n");
      out.write("<!-- Summary -->\r\n");
      out.write("<div class=\"summary_wrap\">\r\n");
      out.write("    <div class=\"summary_top\">\r\n");
      out.write("        <div class=\"summary_top_cont\">\r\n");
      out.write("            <!-- 가격 -->\r\n");
      out.write("            <div class=\"price_wrap\" id=\"summaryTopPrice\">\r\n");
      out.write("                <span class=\"total\">항공운임 등 총액</span>\r\n");
      out.write("                <span class=\"unit summary_currency\">KRW</span>\r\n");
      out.write("                <span class=\"price\" id=\"summary_title_amount\">\r\n");
      out.write("                	");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${totalPrice}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                </span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- 가격 -->\r\n");
      out.write("            <!-- 버튼 -->\r\n");
      out.write("            <div class=\"float--right font0\" id=\"buttonSet\">\r\n");
      out.write("            	<!-- \r\n");
      out.write("                   <button class=\"btn_large gray buttonControl\" id=\"nextStep\" type=\"button\">다음 구간</button>\r\n");
      out.write("                   <button class=\"btn_large gray buttonControl\" id=\"undoStep\" type=\"button\">이전 구간</button>\r\n");
      out.write("                   -->\r\n");
      out.write("               <button class=\"btn_large red buttonControl next\" id=\"checkIn\" style=\"background-color:  rgb(210, 44, 38); color: white;\">다음 단계</button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<!-- Summary -->\r\n");
      out.write("\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("//영문 성 input 정규식\r\n");
      out.write("$(\"#firstName\").keyup(function(event) {\r\n");
      out.write("    if (!(event.keyCode >= 37 && event.keyCode <= 40)) {\r\n");
      out.write("       var inputVal = $(this).val();\r\n");
      out.write("       $(this).val(inputVal.replace(/[^(a-zA-Z)]/gi, '').toUpperCase());\r\n");
      out.write("    }\r\n");
      out.write(" });\r\n");
      out.write("//영문 이름 input 정규식\r\n");
      out.write("$(\"#lastName\").keyup(function(event) {\r\n");
      out.write("    if (!(event.keyCode >= 37 && event.keyCode <= 40)) {\r\n");
      out.write("       var inputVal = $(this).val();\r\n");
      out.write("       $(this).val(inputVal.replace(/[^(a-zA-Z)]/gi, '').toUpperCase());\r\n");
      out.write("    }\r\n");
      out.write(" });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#rp').blur(function(){\r\n");
      out.write("	if($(this).val().length > 12 ){\r\n");
      out.write("		tel_check($(this).val());\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function tel_check(str){\r\n");
      out.write("	var regTel = /^(01[016789]{1}|070|02|0[3-9]{1}[0-9]{1})-[0-9]{3,4}-[0-9]{4}$/;\r\n");
      out.write("	\r\n");
      out.write("	if(!regTel.test(str)) {\r\n");
      out.write("		alert('올바른 전화번호를 입력하세요.');\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("	return true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var x = 0;\r\n");
      out.write("$('.hannaName').blur(function(){\r\n");
      out.write("	if($(this).val()==\"\"){\r\n");
      out.write("		x=1;\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("$('#btn').click(function(){\r\n");
      out.write("	x=0;\r\n");
      out.write("	$('.hn1').each(function(){\r\n");
      out.write("		if($('.hn1 option:eq(0)').prop('selected')){\r\n");
      out.write("		x=3;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('.hn2').each(function(){\r\n");
      out.write("		if($('.hn2 option:eq(0)').prop('selected')){\r\n");
      out.write("		x=3;\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	$('.hn3').each(function(){\r\n");
      out.write("		if($('.hn3 option:eq(0)').prop('selected')){\r\n");
      out.write("		x=3;\r\n");
      out.write("	}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	$('.hannaName').each(function(){\r\n");
      out.write("		if($('.hannaName').val()==\"\"){\r\n");
      out.write("			x=1;\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	if($('#re').val() == ''){\r\n");
      out.write("		x=1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	if($('#rp').val() == ''){\r\n");
      out.write("		x=1;\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	if(x==1){\r\n");
      out.write("		alert(\"모든 항목을 입력하세요.\");\r\n");
      out.write("	}else if(x==3){\r\n");
      out.write("		alert(\"생년월일을 입력하세요.\");\r\n");
      out.write("\r\n");
      out.write("	}else{\r\n");
      out.write("		$(\"#frm\").submit();\r\n");
      out.write("	}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/booking/bookingPage2.jsp(117,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(117,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setEnd(3);
      // /WEB-INF/views/booking/bookingPage2.jsp(117,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \r\n");
            out.write("<table style=\"margin-left: 111px;\"><!-- 성인1 -->\r\n");
            out.write("<tr><td colspan=\"2\"><h4 style=\"font-size: 28px;\">성인 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4></td> </tr>\r\n");
            out.write("\r\n");
            out.write("<tr> \r\n");
            out.write("<td class=\"bth\">성별</td> \r\n");
            out.write("<td class=\"btb\">\r\n");
            out.write("<input type=\"radio\" name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].gender\" value=\"여\" id=\"womana");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"rfchk\" checked=\"checked\"> \r\n");
            out.write("<label for=\"womana");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">여자</label>\r\n");
            out.write("<input type=\"radio\" name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].gender\" value=\"남\" id=\"mana");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" class=\"rfchk\">  \r\n");
            out.write("<label for=\"mana");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">남자</label>\r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">영문명</td> \r\n");
            out.write("<td class=\"btb\">\r\n");
            out.write("<input type=\"text\" placeholder=\"성(신분증언어)\" class=\"hannaName\" name=\"firstName\" id=\"firstName\"> \r\n");
            out.write("<input type=\"text\" placeholder=\"이름(신분증언어)\" class=\"hannaName\" name=\"lastName\" id=\"lastName\"> \r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">생년월일</td>\r\n");
            out.write("<td class=\"btb\"> \r\n");
            out.write("\r\n");
            out.write("<select name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].year\" class=\"hn1\"> \r\n");
            out.write("<option selected=\"selected\">년</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("\r\n");
            out.write("<select name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].month\" class=\"hn2\"> \r\n");
            out.write("<option selected=\"selected\">월</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f2(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("\r\n");
            out.write("<select name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].day\" class=\"hn3\"> \r\n");
            out.write("<option selected=\"selected\">일</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">국적</td>\r\n");
            out.write("<td class=\"btb\">\r\n");
            out.write("	<div class=\"input_wrap\">\r\n");
            out.write("		<input type=\"hidden\" id=\"nationality\" name=\"nationality\">\r\n");
            out.write("							\r\n");
            out.write("		<input class=\"\" id=\"nationCodeExplain\" name=\"nationCodeExplain\" title=\"거주 지역 입력\" type=\"text\" placeholder=\"지역을 검색해주세요.\" value=\"대한민국\">\r\n");
            out.write("		<input id=\"apisNationCode\" name=\"apisNationCode\" type=\"hidden\" value=\"KR\">\r\n");
            out.write("	</div>\r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">개인할인(가는편)</td>\r\n");
            out.write("<td class=\"btb\"> \r\n");
            out.write("<select name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].depCoupon\">\r\n");
            out.write("<option>개인할인 선택 안함</option>\r\n");
            out.write("<option>[30%] 장애인 1~3급</option>\r\n");
            out.write("<option>[10%] 장애인 4~6급</option>\r\n");
            out.write("<option>[30%] 장애인 1~3급 동반 보호자 1인</option>\r\n");
            out.write("<option>[10%] 현역군인(휴가증소지의 의무복무사병)</option>\r\n");
            out.write("<option>[10%] 고엽제 후유증 환자</option>\r\n");
            out.write("<option>[30%] 국가유공상이 4급 동반 보호자 1인</option>\r\n");
            out.write("<option>[30%] 5.18민주유공 1~4급 동반 보호자 1인</option>\r\n");
            out.write("<option>[30%] 국가유공상이 1~3급 동반 보호자 1인</option>\r\n");
            out.write("<option>[30%] 독립유공자 동반 보호자 1인</option>\r\n");
            out.write("<option>[10%] 독립유공자 유족증소지자</option>\r\n");
            out.write("<option>[30%] 독립유공자</option>\r\n");
            out.write("<option>[10%] 국가유공자/5.18민주유공자/월남전 참전유공자 &#38; 유공자 유족증 소지자</option>\r\n");
            out.write("<option>[30%] 국가유공상이자 &#38; 5.18민주유공부상자</option>\r\n");
            out.write("</select>\r\n");
            out.write("\r\n");
            out.write(" </td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("</table><!-- 성인1 -->\r\n");
            out.write("<br><br>\r\n");
            out.write("<hr>\r\n");
            out.write("<br><br>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/booking/bookingPage2.jsp(145,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setBegin(1910);
      // /WEB-INF/views/booking/bookingPage2.jsp(145,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setEnd(2023);
      // /WEB-INF/views/booking/bookingPage2.jsp(145,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVarStatus("status1");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status1.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/booking/bookingPage2.jsp(152,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(152,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setEnd(12);
      // /WEB-INF/views/booking/bookingPage2.jsp(152,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVarStatus("status2");
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status2.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/booking/bookingPage2.jsp(159,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(159,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setEnd(31);
      // /WEB-INF/views/booking/bookingPage2.jsp(159,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVarStatus("status3");
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status3.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/booking/bookingPage2.jsp(210,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bTVO.child != 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write('\r');
          out.write('\n');
          if (_jspx_meth_c_005fforEach_005f4(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\r');
          out.write('\n');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/booking/bookingPage2.jsp(211,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(211,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setEnd(((java.lang.Integer) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bTVO.child}", int.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).intValue());
      // /WEB-INF/views/booking/bookingPage2.jsp(211,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVarStatus("status");
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write(" \r\n");
            out.write("<table style=\"margin-left: 111px;\"><!-- 아이1 -->\r\n");
            out.write("\r\n");
            out.write("<tr><td colspan=\"2\"><h4 style=\"font-size: 28px;\">아이 ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h4></td> </tr>\r\n");
            out.write("\r\n");
            out.write("<tr> \r\n");
            out.write("<td class=\"bth\">성별</td> \r\n");
            out.write("<td class=\"btb\">\r\n");
            out.write("<input type=\"radio\" name=\"caGender\" value=\"여\" id=\"select\" class=\"rfchk\" checked=\"checked\"> \r\n");
            out.write("<label for=\"select\">여자</label>\r\n");
            out.write("<input type=\"radio\" name=\"caGender\" value=\"남\" id=\"select\" class=\"rfchk\">  \r\n");
            out.write("<label for=\"select\">남자</label>\r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">이름</td> \r\n");
            out.write("<td class=\"btb\"><input type=\"text\" placeholder=\"성(신분증언어)\" class=\"hannaName\"  name=\"FirstName\"> \r\n");
            out.write("<input type=\"text\" placeholder=\"이름(신분증언어)\" class=\"hannaName\" name=\"LastName\"> </td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">생년월일</td>\r\n");
            out.write("<td class=\"btb\"> \r\n");
            out.write("\r\n");
            out.write("<select name=\"childList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].year\"> \r\n");
            out.write("<option selected=\"selected\">년</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f5(_jspx_th_c_005fforEach_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("\r\n");
            out.write("<select name=\"childList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].month\"> \r\n");
            out.write("<option selected=\"selected\">월</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f6(_jspx_th_c_005fforEach_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("\r\n");
            out.write("<select name=\"childList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].day\"> \r\n");
            out.write("<option selected=\"selected\">일</option>\r\n");
            if (_jspx_meth_c_005fforEach_005f7(_jspx_th_c_005fforEach_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
              return true;
            out.write("\r\n");
            out.write("</select> \r\n");
            out.write("</td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("	<td class=\"bth\">국적</td>\r\n");
            out.write("	<td class=\"btb\">\r\n");
            out.write("	<input type=\"text\" placeholder=\"대한민국\" name=\"adultList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].memberNum\" class=\"mnum\" readonly=\"readonly\">\r\n");
            out.write("	<input type=\"button\" value=\"국적 검색\" class=\"mbtn\">\r\n");
            out.write("	</td>\r\n");
            out.write("	</tr>\r\n");
            out.write("\r\n");
            out.write("<tr>\r\n");
            out.write("<td class=\"bth\">개인할인(가는편)</td>\r\n");
            out.write("<td class=\"btb\"> \r\n");
            out.write("<select name=\"childList[");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status.index-1}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("].depCoupon\">\r\n");
            out.write("<option>개인할인 선택 안함</option>\r\n");
            out.write("<option selected=\"selected\">[25%] 아이(만2~13세미만)할인</option>\r\n");
            out.write("<option>[50%] 국가유공상이자1~4급 동반 소아1인</option>\r\n");
            out.write("<option>[50%] 5.18부상 동반 소아1인</option>\r\n");
            out.write("<option>[50%] 독립유공자 동반 소아1인</option>\r\n");
            out.write("<option>[50%] 1~3급 소아 장애인 할인</option>\r\n");
            out.write("<option>[30%] 4~6급 소아 장애인 할인</option>\r\n");
            out.write("<option>[50%] 장애인(1~3급)동반 소아</option>\r\n");
            out.write("<option>[25%] 청소년(만14~18세미만)할인</option>\r\n");
            out.write("</select>\r\n");
            out.write("\r\n");
            out.write(" </td>\r\n");
            out.write("</tr>\r\n");
            out.write("\r\n");
            out.write("</table><!-- 아이1 -->\r\n");
            out.write("<div style=\"padding-left: 117px; padding-top: 18px;\">소아/유아 동반 시, 반드시 나이를 확인할 수 있는 서류를 준비하시기 바랍니다.</div>\r\n");
            out.write("<hr>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f4);
      // /WEB-INF/views/booking/bookingPage2.jsp(238,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setBegin(1910);
      // /WEB-INF/views/booking/bookingPage2.jsp(238,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setEnd(2020);
      // /WEB-INF/views/booking/bookingPage2.jsp(238,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVarStatus("status1");
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status1.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f6 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f6_reused = false;
    try {
      _jspx_th_c_005fforEach_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f4);
      // /WEB-INF/views/booking/bookingPage2.jsp(245,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(245,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setEnd(12);
      // /WEB-INF/views/booking/bookingPage2.jsp(245,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f6.setVarStatus("status2");
      int[] _jspx_push_body_count_c_005fforEach_005f6 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f6 = _jspx_th_c_005fforEach_005f6.doStartTag();
        if (_jspx_eval_c_005fforEach_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status2.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f6.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f6[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f6.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f6.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f6);
      _jspx_th_c_005fforEach_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f6, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f6_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f7 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f7_reused = false;
    try {
      _jspx_th_c_005fforEach_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f4);
      // /WEB-INF/views/booking/bookingPage2.jsp(252,0) name = begin type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setBegin(1);
      // /WEB-INF/views/booking/bookingPage2.jsp(252,0) name = end type = int reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setEnd(31);
      // /WEB-INF/views/booking/bookingPage2.jsp(252,0) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f7.setVarStatus("status3");
      int[] _jspx_push_body_count_c_005fforEach_005f7 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f7 = _jspx_th_c_005fforEach_005f7.doStartTag();
        if (_jspx_eval_c_005fforEach_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("<option>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${status3.index}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f7.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f7[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f7.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f7.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fend_005fbegin.reuse(_jspx_th_c_005fforEach_005f7);
      _jspx_th_c_005fforEach_005f7_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f7, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f7_reused);
    }
    return false;
  }
}
