/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2023-01-25 15:13:36 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.common.model.vo.Attachment;
import com.user.board.recipe.model.vo.Board;
import com.user.member.model.vo.Member;
import com.user.member.model.vo.MyPage;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/views/common/footer.jsp", Long.valueOf(1668572662000L));
    _jspx_dependants.put("/views/common/menubar.jsp", Long.valueOf(1668572662000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.user.member.model.vo.Member");
    _jspx_imports_classes.add("com.user.member.model.vo.MyPage");
    _jspx_imports_classes.add("com.common.model.vo.Attachment");
    _jspx_imports_classes.add("com.user.board.recipe.model.vo.Board");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	Board b = (Board) request.getAttribute("b");
	Attachment at = (Attachment)request.getAttribute("Attachment");

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>mainpage</title>\r\n");
      out.write("<style>\r\n");
      out.write(".img-fluid {\r\n");
      out.write("  width: 850px;\r\n");
      out.write("  height: 850px;\r\n");
      out.write("  object-fit: cover;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"apple-touch-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/img/apple-icon.png\">\r\n");
      out.write("	\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/common/iconCook.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"template/assets/css/fontawesome.min.css\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
 
	String contextPath = request.getContextPath();
	Member loginUser = (Member)session.getAttribute("loginUser");
	MyPage mp = (MyPage)session.getAttribute("mp");
	//로그인 성공시 띄워줄 알람 메세지
	String alertMsg = (String)session.getAttribute("alertMsg");
	

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>menubar</title>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	<!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"apple-touch-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/img/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/fontawesome.min.css\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<script>\r\n");
      out.write("	let msg = \"");
      out.print(alertMsg);
      out.write("\";\r\n");
      out.write("	\r\n");
      out.write("	if(msg !=\"null\"){\r\n");
      out.write("		alert(msg);\r\n");
      out.write("		//로그인 성공때 띄운 session삭제\r\n");
      out.write("		");
session.removeAttribute("alertMsg");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write(" <!-- Start Top Nav -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light bg-yellow d-none d-lg-block\" id=\"templatemo_nav_top\">\r\n");
      out.write("        <div class=\"container text-light\">\r\n");
      out.write("            <div class=\"w-100 d-flex justify-content-between\">\r\n");
      out.write("                <div>\r\n");
      out.write("                    <i class=\"fa fa-envelope mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"></a>\r\n");
      out.write("                    <i class=\"fa fa-phone mx-2\"></i>\r\n");
      out.write("                    <a class=\"navbar-sm-brand text-light text-decoration-none\"></a>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://fb.com/\" target=\"_blank\" rel=\"sponsored\"><i class=\"fab fa-facebook-f fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.instagram.com/\" target=\"_blank\"><i class=\"fab fa-instagram fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://twitter.com/\" target=\"_blank\"><i class=\"fab fa-twitter fa-sm fa-fw me-2\"></i></a>\r\n");
      out.write("                    <a class=\"text-light\" href=\"https://www.linkedin.com/\" target=\"_blank\"><i class=\"fab fa-linkedin fa-sm fa-fw\"></i></a>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Close Top Nav -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Header -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-lg navbar-light shadow\">\r\n");
      out.write("        <div class=\"container d-flex justify-content-between align-items-center\">\r\n");
      out.write("			<!-- 로고 -->\r\n");
      out.write("            <a class=\"navbar-brand text-success logo h1 align-self-center\" href=\"index.jsp\">\r\n");
      out.write("				<img src=\"");
      out.print( contextPath );
      out.write("/resources/image/common/logo.png\" class=\"logo\" width=\"200px\" height=\"50px\">\r\n");
      out.write("            </a>\r\n");
      out.write("\r\n");
      out.write("            <button class=\"navbar-toggler border-0\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#templatemo_main_nav\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("                <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("	\r\n");
      out.write("			<!-- 게시판 -->\r\n");
      out.write("            <div class=\"align-self-center collapse navbar-collapse flex-fill  d-lg-flex justify-content-lg-between\" id=\"templatemo_main_nav\">\r\n");
      out.write("                <div class=\"flex-fill\">\r\n");
      out.write("                    <ul class=\"nav navbar-nav d-flex justify-content-between mx-lg-auto\">\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/list.re?currentPage=1\"><b>Recipe Board</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath);
      out.write("/list.op?currentPage=1\"><b>Open Board</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/list.qa?currentPage=1\"><b>Q&A</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/list.mo?currentPage=1\"><b>Monthly Best</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/list.in?currentPage=1\"><b>Info</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <!-- grade_code가 'M1'일 경우에만 보이도록 하기 -->\r\n");
      out.write("                        ");
if(loginUser != null && loginUser.getGradeCode().equals("M1")){ 
      out.write("\r\n");
      out.write("                        <li class=\"nav-item\">\r\n");
      out.write("                            <a class=\"nav-link\" href=\"");
      out.print(contextPath );
      out.write("/adminBoardView.bo\"><b>Manager</b></a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        ");
} 
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("               <div class=\"navbar align-self-center d-flex\">\r\n");
      out.write("                    <div class=\"d-lg-none flex-sm-fill mt-3 mb-4 col-7 col-sm-auto pr-3\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control\" id=\"inputMobileSearch\" placeholder=\"Search ...\">\r\n");
      out.write("                            <div class=\"input-group-text\">\r\n");
      out.write("                                <i class=\"fa fa-fw fa-search\">\r\n");
      out.write("                            	</i>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 검색창 -->\r\n");
      out.write("                    <a class=\"nav-icon d-none d-lg-inline\" href=\"");
      out.print( contextPath);
      out.write("/search.re\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-search text-dark mr-2\"></i>\r\n");
      out.write("                    </a>\r\n");
      out.write("                    \r\n");
      out.write("                    <!-- 로그인창 -->\r\n");
      out.write("                   ");
if(loginUser==null){ 
      out.write("\r\n");
      out.write("                    <a class=\"nav-icon position-relative text-decoration-none\" href=\"");
      out.print( contextPath);
      out.write("/views/user/loginForm.jsp\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-user text-dark mr-3\"></i>\r\n");
      out.write("                        <span\r\n");
      out.write("                            class=\"position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  	");
}else if(loginUser!=null){ 
      out.write("\r\n");
      out.write("                  	\r\n");
      out.write("                  	<a href=\"");
      out.print(contextPath);
      out.write("/views/user/myPage.jsp\">");
      out.print(mp.getNickName());
      out.write("</a>\r\n");
      out.write("                  	 　\r\n");
      out.write("                  	<a class=\"nav-icon position-relative text-decoration-none\" href=\"");
      out.print(contextPath);
      out.write("/logout.me\">\r\n");
      out.write("                        <i class=\"fa fa-fw fa-user-times text-dark mr-3\"></i>\r\n");
      out.write("                        <span\r\n");
      out.write("                            class=\"position-absolute top-0 left-100 translate-middle badge rounded-pill bg-light text-dark\"></span>\r\n");
      out.write("                    </a>\r\n");
      out.write("                  		\r\n");
      out.write("                  	");
} 
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("    <!-- Close Header -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/js/templatemo.js\"></script>\r\n");
      out.write("    <script src=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/js/custom.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("	\r\n");
      out.write("     \r\n");
      out.write("    <br><br><br>\r\n");
      out.write("    \r\n");
      out.write("    <div align=\"center\" class=\"tm\"><b>Today's Menu</b></div>\r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    \r\n");
      out.write("    <!-- Start Banner Hero -->\r\n");
      out.write("    <div id=\"template-mo-zay-hero-carousel\" class=\"carousel slide\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <ol class=\"carousel-indicators\">\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"1\"></li>\r\n");
      out.write("            <li data-bs-target=\"#template-mo-zay-hero-carousel\" data-bs-slide-to=\"2\"></li>\r\n");
      out.write("        </ol>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                        <a href=\"");
      out.print(contextPath );
      out.write("/detail.re?bno=5\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"resources/image/recipeImg/39665_T.jpg\" alt=\"\">\r\n");
      out.write("                        </a>   \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-left align-self-center\">\r\n");
      out.write("                                <h1 class=\"h1 text-yellow\"><b>Today's menu</b></h1>\r\n");
      out.write("                                <h3 class=\"h2\">오늘은 이 메뉴 어때요?</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                	\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                            <a href=\"");
      out.print(contextPath );
      out.write("/detail.re?bno=7\">\r\n");
      out.write("                            	<img class=\"img-fluid\" src=\"resources/image/recipeImg/5836_T.jpg\" alt=\"\">\r\n");
      out.write("                            </a> \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-left\">\r\n");
      out.write("                                <h1 class=\"h1\"><b>Today's menu</b></h1>\r\n");
      out.write("                                <h3 class=\"h2\">오늘은 이 메뉴 어때요?</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                	\r\n");
      out.write("                                	\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <div class=\"container\">\r\n");
      out.write("                    <div class=\"row p-5\">\r\n");
      out.write("                        <div class=\"mx-auto col-md-8 col-lg-6 order-lg-last\">\r\n");
      out.write("                        <a href=\"");
      out.print(contextPath );
      out.write("/detail.re?bno=9\">\r\n");
      out.write("                            <img class=\"img-fluid\" src=\"resources/image/recipeImg/73679_T.jpg\" alt=\"\">\r\n");
      out.write("                          </a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-6 mb-0 d-flex align-items-center\">\r\n");
      out.write("                            <div class=\"text-align-left\">\r\n");
      out.write("                                <h1 class=\"h1\"><b>Today's menu</b></h1>\r\n");
      out.write("                                <h3 class=\"h2\">오늘은 이 메뉴 어때요?</h3>\r\n");
      out.write("                                <p>\r\n");
      out.write("                                	\r\n");
      out.write("                                </p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <a class=\"carousel-control-prev text-decoration-none w-auto ps-3\" href=\"#template-mo-zay-hero-carousel\" role=\"button\" data-bs-slide=\"prev\">\r\n");
      out.write("            <i class=\"fas fa-chevron-left\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("        <a class=\"carousel-control-next text-decoration-none w-auto pe-3\" href=\"#template-mo-zay-hero-carousel\" role=\"button\" data-bs-slide=\"next\">\r\n");
      out.write("            <i class=\"fas fa-chevron-right\"></i>\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!-- End Banner Hero -->\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <br><br>\r\n");
      out.write("    \r\n");
      out.write("     \r\n");
      out.write("    <!-- Start Script -->\r\n");
      out.write("    <script src=\"assets/js/jquery-1.11.0.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/jquery-migrate-1.2.1.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/templatemo.js\"></script>\r\n");
      out.write("    <script src=\"assets/js/custom.js\"></script>\r\n");
      out.write("    <!-- End Script -->\r\n");
      out.write("     \r\n");
      out.write("    <br><br>\r\n");
      out.write("     ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("	<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("	<link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<!-- Latest compiled and minified CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <!-- jQuery library -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("    <!-- Popper JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <!-- Latest compiled JavaScript -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	\r\n");
      out.write("	<link rel=\"apple-touch-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/img/apple-icon.png\">\r\n");
      out.write("    <link rel=\"shortcut icon\" type=\"image/x-icon\" href=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/common/iconCook.png\">\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/bootstrap.min.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/templatemo.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/custom.css\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Load fonts style after rendering the layout styles -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Roboto:wght@100;200;300;400;500;700;900&display=swap\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/template/assets/css/fontawesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	 <!-- Start Footer -->\r\n");
      out.write("    <footer class=\"bg-grey border-top border-black\" id=\"tempaltemo_footer\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-success border-bottom pb-3 border-black\" >\r\n");
      out.write("                    	<img src=\"");
      out.print(request.getContextPath() );
      out.write("/resources/image/common/logo.png\" class=\"logo\" width=\"150px\" height=\"30px\">\r\n");
      out.write("                    </h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-black footer-link-list\">\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fas fa-map-marker-alt fa-fw text-black\"></i>\r\n");
      out.write("                                                                       주소 : 서울 영등포구 선유동2로 57 이레빌딩 20층 E사무실\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-phone fa-fw text-black\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"tel:010-020-0340\">tel:010-1111-2222</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li>\r\n");
      out.write("                            <i class=\"fa fa-envelope fa-fw text-black\"></i>\r\n");
      out.write("                            <a class=\"text-decoration-none\" href=\"mailto:info@company.com\">email: cookcook@company.com</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-black border-bottom pb-3 border-black\" >Board</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-black footer-link-list\">\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.re?currentPage=1\">Recipe Board</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.op?currentPage=1\">Open Board </a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.qa?currentPage=1\">Q&A</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.mo?currentPage=1\">Monthly Best</a></li>\r\n");
      out.write("                        <li><a class=\"text-decoration-none\" href=\"");
      out.print(request.getContextPath());
      out.write("/list.in?currentPage=1\">Info</a></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-md-4 pt-5\">\r\n");
      out.write("                    <h2 class=\"h2 text-black border-bottom pb-3 border-black\">Member Info</h2>\r\n");
      out.write("                    <ul class=\"list-unstyled text-black footer-link-list\">\r\n");
      out.write("                    	<li><h6 class=\"text-decoration-none\">김남호</h6></li>\r\n");
      out.write("                    	<li><h6 class=\"text-decoration-none\">김소이</h6></li>\r\n");
      out.write("                        <li><h6 class=\"text-decoration-none\">이지윤</h6></li>\r\n");
      out.write("                        <li><h6 class=\"text-decoration-none\">원종우</h6></li>\r\n");
      out.write("                        <li><h6 class=\"text-decoration-none\">전은덕</h6></li>\r\n");
      out.write("                        <li><h6 class=\"text-decoration-none\">정혜진</h6></li>\r\n");
      out.write("                    </ul>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row text-black mb-4\">\r\n");
      out.write("                <div class=\"col-12 mb-3\">\r\n");
      out.write("                    <div class=\"w-100 my-3 border-top border-black\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-auto me-auto\">\r\n");
      out.write("                      	전화문의 - 10:00 ~ 12:00, 13:00 ~ 17:00 / 주말 공휴일 휴무\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"w-100 bg-yellow py-3\">\r\n");
      out.write("            <div class=\"container\">\r\n");
      out.write("                <div class=\"row pt-2\">\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                        <p class=\"text-left text-white\">\r\n");
      out.write("                            Copyright &copy; 2022 밥조 \r\n");
      out.write("                            | Designed by 밥조\r\n");
      out.write("                        </p>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <!-- End Footer -->\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("	\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
